# Site settings
name: Less Or More
email: wyingj@qq.com
author: Joyce Ng
url: http://www.hifreud.com
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/Joyce-Ng/
baseurl: "/Blog"
description: Actually, less is more!
meta_description: Joyce;个人博客;功不唐捐;玉汝于成;生命不止;折腾不休
motto: Just do IT.
banner: 我爱学习，学习使我快乐。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
#gems: [jekyll-paginate, jekyll-gist]
#paginate: 3

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Joyce-Ng

# Build settings

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : windjoy258
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
